In [1]:
import pandas as pd
import numpy as np

In [11]:
#Importing data
df = pd.read_csv('spam.csv', encoding='latin-1')
df.drop(columns=['Unnamed: 2','Unnamed: 3',	'Unnamed: 4'], inplace = True)
df.columns = ['label', 'message']
df

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [13]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\thari.lokesh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [14]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [19]:
#Data cleaning and preprocessing
corpus = []
for i in range(len(df)):
    review = re.sub('[^a-zA-Z]',' ', df['message'][i])
    review = review.lower()
    review = review.split()
    [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [37]:
# Creating bag of words model:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500, binary=True)
X = cv.fit_transform(corpus).toarray()

array(['aah', 'aathi', 'abi', ..., 'yun', 'yup', 'zed'], dtype=object)

In [38]:
pd.DataFrame(X, columns=cv.get_feature_names_out())

,aah,aathi,abi,abiola,able,about,abt,abta,ac,acc,...,you,your,yours,yourself,yr,yrs,yummy,yun,yup,zed
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11139,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11140,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11141,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11142,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11143,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
# Preprocessing using Lemmatization
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()

In [32]:
for i in range(len(df)):
    review = re.sub('[^a-zA-Z]',' ', df['message'][i])
    review = review.lower()
    review = review.split()
    [lemma.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [39]:
cv = CountVectorizer(max_features=2500, binary=True)
X = cv.fit_transform(corpus).toarray()
pd.DataFrame(X, columns=cv.get_feature_names_out())

,aah,aathi,abi,abiola,able,about,abt,abta,ac,acc,...,you,your,yours,yourself,yr,yrs,yummy,yun,yup,zed
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11139,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11140,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11141,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11142,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11143,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### N Gram:
<p>sklearn offers a parameter known as N gram for creation of BOW. 
<p>Consider the below set of messages:
<li>'Boy is Good'
<li>'Boy is not Good'
<p>The vector representation of the above would be [1,1,1,0] and [1,1,1,1] given the vocabulary is ['Boy','is','good','not']
<p>It can be observed that the cosine similarity of the above two vectors is high but the meaning implies otherwise.
<p>To counter this issue, N gram can be used, which helps adding combination of 2 or more words to vocabulary.
<p>for, N gram = [1,2] ---> vocab: ['Boy','is','good','not', 'Boy is', 'is good', 'good not'....]
<p>vect representation: sentence 1 ---> [1,1,1,0,1,1,0] and sentence 2 ---> [1,1,1,1,1,1,1]
<p>Now the similarity is reduced.

In [40]:
# Using N gram: 
# Combination of unigram and bigram = [1,2]
# Combination of unigram and trigram = [1,3]
# Combination of bigram and trigram = [2,3] so on..

cv = CountVectorizer(max_features=2500, binary=True,ngram_range=(1, 2))
X = cv.fit_transform(corpus).toarray()
pd.DataFrame(X, columns=cv.get_feature_names_out())

,abiola,able,able to,about,about me,about the,about this,about you,abt,ac,...,your number,your phone,your prize,your reply,yours,yours call,yourself,yr,yrs,yup
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11139,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11140,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11141,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11142,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11143,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0